name: gasapp
description: A new Flutter application.

publish_to: 'none'

version: 1.0.7+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  flutter_launcher_icons: ^0.9.0
#
#flutter_icons:
#  image_path: "assets/icon_agzs.png"
#  android: true
#  ios: true

  flutter_localizations:
    sdk: flutter
  mask_text_input_formatter: ^1.2.1
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  geolocator: ^7.0.1
  google_maps_flutter: ^2.0.2
  cupertino_icons: ^1.0.0
  shared_preferences: ^2.0.5
  http: ^0.13.1
  # wakelock: ^0.5.0+2
  flutter_html: ^1.3.0
  intl: ^0.17.0
  easy_localization: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0

flutter_icons:
  image_path: "assets/icon_agzs_old.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/